### ISSUE TITLE
could not compile `native` due to previous error

### ISSUE THREAD

**Issue by ehijzengsf** [rustytsuki/rust-office#1]
after running cargo run -p native

  = note: Undefined symbols for architecture x86_64:
            "_docx_area_size", referenced from:
                shell::docx_app::viewport::Viewport::update::_$u7b$$u7b$closure$u7d$$u7d$::h5859e708f8a519e2 in libshell.rlib(shell.3kg6qpe5qnqsw9rh.rcgu.o)
            "_docx_get_zoom", referenced from:
                _$LT$shell..docx_app..DOCXApp$u20$as$u20$eframe..epi..App$GT$::update::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf1df812a550f8358 in libshell.rlib(shell.4v1nbiutq2ivenmd.rcgu.o)
            "_docx_set_zoom", referenced from:
                _$LT$shell..docx_app..DOCXApp$u20$as$u20$eframe..epi..App$GT$::update::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf1df812a550f8358 in libshell.rlib(shell.4v1nbiutq2ivenmd.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `native` due to previous error

**Comment by rustytsuki** [comment]
I've not update the engine core, this project is still in a very early stage.
